# Source: lighthouse/templates/tekton-controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-tekton-controller
  labels:
    chart: "lighthouse-1.22.0"
    app: lighthouse-tekton-controller
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
    meta.helm.sh/release-namespace: 'jx'
    wave.pusher.com/update-on-config-change: 'true'
  namespace: jx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse-tekton-controller
  template:
    metadata:
      labels:
        app: lighthouse-tekton-controller
      annotations: {jenkins-x.io/hash: 'e94ad05d85d7ac9b60f338c3128f8e181f9ab3ea97f4232d29730da149fe2fff'}
    spec:
      serviceAccountName: lighthouse-tekton-controller
      containers:
      - name: lighthouse-tekton-controller
        image: ghcr.io/jenkins-x/lighthouse-tekton-controller:1.22.0
        imagePullPolicy: IfNotPresent
        args:
        - --namespace=jx
        - --dashboard-url=http://dashboard-jx.jenkinsx.corp.angoo.io
        - --dashboard-template=namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}
        - --enable-rerun-status-update=false
        ports:
        - name: metrics
          containerPort: 8080
        env:
        - name: "LOGRUS_FORMAT"
          value: "json"
        - name: LOGRUS_SERVICE
          value: "lighthouse"
        - name: LOG_LEVEL
          value: "info"
        - name: LOGRUS_SERVICE_VERSION
          value: "1.22.0"
        - name: LOGRUS_STACK_SKIP
          value: ""
        - name: DEFAULT_PIPELINE_RUN_SERVICE_ACCOUNT
          value: "tekton-bot"
        - name: DEFAULT_PIPELINE_RUN_TIMEOUT
          value: "2h0m0s"
        - name: FILE_BROWSER
          value: "git"
        - name: JX_DEFAULT_IMAGE
          value: "ghcr.io/jenkins-x/builder-maven:2.1.149-768"
        - name: LIGHTHOUSE_DASHBOARD_TEMPLATE
          value: "namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}"
        - name: LIGHTHOUSE_VERSIONSTREAM_JENKINS_X_JX3_PIPELINE_CATALOG
          value: "ac17d3562f6bdecb91178f5f030f5f759edcd9ea"
        envFrom:
        - secretRef:
            name: jx-boot-job-env-vars
            optional: true
        securityContext: {}
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
      terminationGracePeriodSeconds: 180
      nodeSelector: {}
      affinity: {}
      tolerations: []
      securityContext: {}
